/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.derick.smartcalculator.view;

import javax.swing.JOptionPane;

/**
 *
 * @author derickfelix
 */
public class MainForm extends javax.swing.JFrame {

    private char guestResult;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        configComponents();
    }

    private void configComponents() {
        this.spnDensity.setEnabled(false);
        this.spnMass.setEnabled(false);
        this.spnVolume.setEnabled(false);
        this.lblResult.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JPanel();
        lblMainImage = new javax.swing.JLabel();
        spnDensity = new javax.swing.JSpinner();
        spnMass = new javax.swing.JSpinner();
        spnVolume = new javax.swing.JSpinner();
        lblDensity = new javax.swing.JLabel();
        lblMass = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        paneButtons = new javax.swing.JPanel();
        btnChangeDensity = new javax.swing.JButton();
        btnChangeMass = new javax.swing.JButton();
        btnChangeVolume = new javax.swing.JButton();
        paneResult = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        lblTitleResult = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        paneName = new javax.swing.JPanel();
        paneAuthor = new javax.swing.JLabel();
        paneDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Density Calculator");
        setResizable(false);

        paneMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMainImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/derick/smartcalculator/res/density-main-image.png"))); // NOI18N

        spnDensity.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        spnMass.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        spnVolume.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        lblDensity.setText("Density");

        lblMass.setText("Mass");

        lblVolume.setText("Volume");

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblDensity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblMass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnMass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVolume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMainImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDensity)
                    .addComponent(lblMass)
                    .addComponent(spnMass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVolume))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        paneButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnChangeDensity.setText("Density");
        btnChangeDensity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeDensityActionPerformed(evt);
            }
        });

        btnChangeMass.setText("Mass");
        btnChangeMass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeMassActionPerformed(evt);
            }
        });

        btnChangeVolume.setText("Volume");
        btnChangeVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeVolumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneButtonsLayout = new javax.swing.GroupLayout(paneButtons);
        paneButtons.setLayout(paneButtonsLayout);
        paneButtonsLayout.setHorizontalGroup(
            paneButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangeMass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeDensity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paneButtonsLayout.setVerticalGroup(
            paneButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnChangeDensity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeMass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeVolume)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCalculate.setText("Calculate");
        btnCalculate.setToolTipText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblTitleResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTitleResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleResult.setText("Guest");
        lblTitleResult.setToolTipText("Result");

        lblResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(42, 42, 42));
        lblResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneResultLayout = new javax.swing.GroupLayout(paneResult);
        paneResult.setLayout(paneResultLayout);
        paneResultLayout.setHorizontalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitleResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneResultLayout.setVerticalGroup(
            paneResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addComponent(lblTitleResult)
                .addGap(18, 18, 18)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        paneName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paneAuthor.setText("Derick Felix");

        paneDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paneDate.setText("2017");

        javax.swing.GroupLayout paneNameLayout = new javax.swing.GroupLayout(paneName);
        paneName.setLayout(paneNameLayout);
        paneNameLayout.setHorizontalGroup(
            paneNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneNameLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(paneNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneDate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneAuthor))
                .addGap(28, 28, 28))
        );
        paneNameLayout.setVerticalGroup(
            paneNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneNameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(paneAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneDate)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setZeroValues() {
        this.spnDensity.setValue((double) 0);
        this.spnMass.setValue((double) 0);
        this.spnVolume.setValue((double) 0);
        this.lblResult.setText("");
    }

    private String removeLastZero(String number) {

        String string = "";
        String noPoint = "";
        if (number.endsWith("0")) {
            for (int i = 0; i < number.length() - 1; i++) {
                // get the value of the number
                string += number.charAt(i);
            }

            if (string.endsWith("0")) {
                for (int i = 0; i < string.length() - 2; i++) {
                    // get the value of the number
                    noPoint += number.charAt(i);
                }

                return noPoint;
            }

            return string;
        }

        return number;
    }
     private String formateNumber(Object arg) {
        String formated;
        formated = String.format("%.2f", arg);
        formated = removeLastZero(formated);
        
        return formated;
    }

   
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        double density = (double) this.spnDensity.getValue();
        double mass = (double) this.spnMass.getValue();
        double volume = (double) this.spnVolume.getValue();

        String result = "<html>";
       
        switch (guestResult) {

            case 'd':
                density += mass / volume;

                result += formateNumber(density) + " mass / volume<sup>3</sup>";
                break;
            case 'm':
                mass += volume * density;   
                result += formateNumber(mass) + " mass";
                break;
            case 'v':
                volume += mass / density;    
                result += formateNumber(volume) + " volume<sup>3</sup>";
                break;
            default:
                JOptionPane.showMessageDialog(null, "You did not choice a value to find out yet.");
                break;
        }
        result += "</html>";
        this.lblResult.setText(result);

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnChangeDensityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeDensityActionPerformed
        // TODO add your handling code here:

        this.spnDensity.setEnabled(false);
        this.spnMass.setEnabled(true);
        this.spnVolume.setEnabled(true);
        this.guestResult = 'd';
        this.lblTitleResult.setText("Density");
        setZeroValues();
    }//GEN-LAST:event_btnChangeDensityActionPerformed

    private void btnChangeMassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeMassActionPerformed
        // TODO add your handling code here:
        this.spnDensity.setEnabled(true);
        this.spnMass.setEnabled(false);
        this.spnVolume.setEnabled(true);
        this.guestResult = 'm';
        this.lblTitleResult.setText("Mass");
        setZeroValues();
    }//GEN-LAST:event_btnChangeMassActionPerformed

    private void btnChangeVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeVolumeActionPerformed
        // TODO add your handling code here:
        this.spnDensity.setEnabled(true);
        this.spnMass.setEnabled(true);
        this.spnVolume.setEnabled(false);
        this.guestResult = 'v';
        this.lblTitleResult.setText("Volume");
        setZeroValues();
    }//GEN-LAST:event_btnChangeVolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optispnDensity        
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnChangeDensity;
    private javax.swing.JButton btnChangeMass;
    private javax.swing.JButton btnChangeVolume;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDensity;
    private javax.swing.JLabel lblMainImage;
    private javax.swing.JLabel lblMass;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitleResult;
    private javax.swing.JLabel lblVolume;
    private javax.swing.JLabel paneAuthor;
    private javax.swing.JPanel paneButtons;
    private javax.swing.JLabel paneDate;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneMain1;
    private javax.swing.JPanel paneMain2;
    private javax.swing.JPanel paneName;
    private javax.swing.JPanel paneResult;
    private javax.swing.JSpinner spnDensity;
    private javax.swing.JSpinner spnMass;
    private javax.swing.JSpinner spnVolume;
    // End of variables declaration//GEN-END:variables
}
